import React, { useState, createContext } from "react";
import Head from "next/head";
import LapChart from "../components/lap-chart.component";

import { server, years } from "../config";

// const SelctionsContext = createContext({

// })


export default function Home({ gp }) {
  const [year, setYear] = useState(2018);
  const handleChange = (year) => {
    setYear(year);
  };

  return (
    <div className="">
      <Head>
        <title>F1 Nerds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <LapChart years={years} gp={gp} />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const gp_res = await fetch(`https://ergast.com/api/f1/2020.json`);
  const gp_json = await gp_res.json();
  const gp = gp_json.MRData.RaceTable.Races.map((race) => ({
    race: race.Circuit.circuitName,
  }));

  return {
    props: {
      gp,
    },
  };
}
