import { useState, createContext } from "react";
import Head from "next/head";
import BackToTop from "../components/back-to-top.component";
import Footer from "../components/footer.component";
import LapChart from "../components/lap-chart.component";
import Telemetry from "../components/telemetry.component";

export const SelectionsContext = createContext();

export default function Home() {
  const [year, setYear] = useState();
  const [gp, setGp] = useState();
  const [session, setSession] = useState();
  const [selectedDrivers, setSelectedDrivers] = useState();
  const [telemetrySelections, setTelemetrySelections] = useState([]);
  const value = {
    year,
    setYear,
    gp,
    setGp,
    session,
    setSession,
    selectedDrivers,
    setSelectedDrivers,
    telemetrySelections,
    setTelemetrySelections,
  };

  return (
    <div className="min-h-screen min-w-screen">
      <Head>
        <title>F1 Nerds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-extralight">
        <div className="text-center m-auto py-3 text-5xl sticky top-0 bg-slate-500 z-40 bg-opacity-30 backdrop-blur-sm">
          F1 Nerds
        </div>
        <div className="flex flex-col content-center">
          <SelectionsContext.Provider value={value}>
            <LapChart />
            <Telemetry />
          </SelectionsContext.Provider>
          <Footer />
          <BackToTop />
        </div>
      </main>
    </div>
  );
}
